### ISSUE TITLE
使用部分汉字提示不支持的语言：ko

### ISSUE THREAD

**Issue by ABKQPO** [Redmomn/nonebot-plugin-vits-tts#1]
例如当我使用`凯瑟琳说瓦`就会出现这种情况，请问是有什么问题吗，格字也会出现这种问题

**Comment by Redmomn** [comment]
配置腾讯云api了吗，如果没有就是用的langdetect识别语种，准确率不是很高，另外腾讯云识别语种也可能会因为文本量太少出现不准确的情况

**Comment by ABKQPO** [comment]
配置了腾讯云的api，我试试长文本语音
