### ISSUE TITLE
插件安装失败

### ISSUE THREAD

**Issue by danel-phang** [Redmomn/nonebot-plugin-vits-tts#5]
<img width="1280" alt="image" src="https://github.com/Redmomn/nonebot-plugin-vits-tts/assets/145145476/38371b95-f32f-43fc-aba0-ae39da926d0f">
求大佬们帮忙看一下

**Comment by Redmomn** [comment]
换py3.10试试，感觉是python版本的问题，另外可以把完整的报错日志粘贴过来

**Comment by Redmomn** [comment]
参考一下这个解决方案
https://segmentfault.com/a/1190000044275585

**Comment by danel-phang** [comment]
> 换py3.10试试，感觉是python版本的问题，另外可以把完整的报错日志粘贴过来

我换成了py3.11问题解决了
