### ISSUE TITLE
一些反馈

### ISSUE THREAD

**Issue by togawasakikom** [Redmomn/nonebot-plugin-vits-tts#8]
这一行是不是并不需要，req 并不是 HttpProfile 类的属性或方法，每次try执行到这里都会退出
![屏幕截图 2024-04-30 175555](https://github.com/Redmomn/nonebot-plugin-vits-tts/assets/165572321/dae7aa43-579d-4cc3-a57b-7882bfb6d8f5)

**Comment by Redmomn** [comment]
对，这里应该是写错了，我改改
